# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1338, 745)
        MainWindow.setStyleSheet("QPushButton{\n"
"    color:black;\n"
"    background-color: transparent;\n"
"    border-radius: 9px;\n"
"}\n"
"QPushButton:hover{\n"
"    color:white;\n"
"    background-color: rgb(47, 47, 47);\n"
"}\n"
"QPushButton:pressed{\n"
"    color:black;\n"
"    background-color: rgb(216, 216, 216);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tabs = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tabs.setFont(font)
        self.tabs.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabs.setObjectName("tabs")
        self.Home = QtWidgets.QWidget()
        self.Home.setObjectName("Home")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Home)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.mai_text = QtWidgets.QLabel(self.Home)
        self.mai_text.setMaximumSize(QtCore.QSize(16777215, 48))
        font = QtGui.QFont()
        font.setFamily("Game Of Squids")
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.mai_text.setFont(font)
        self.mai_text.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mai_text.setFocusPolicy(QtCore.Qt.NoFocus)
        self.mai_text.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.mai_text.setStyleSheet("*{\n"
"    color: rgb(20, 20, 20);\n"
"}")
        self.mai_text.setInputMethodHints(QtCore.Qt.ImhNone)
        self.mai_text.setTextFormat(QtCore.Qt.MarkdownText)
        self.mai_text.setAlignment(QtCore.Qt.AlignCenter)
        self.mai_text.setWordWrap(False)
        self.mai_text.setObjectName("mai_text")
        self.verticalLayout_2.addWidget(self.mai_text)
        self.frame = QtWidgets.QFrame(self.Home)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(300, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit.setMaximumSize(QtCore.QSize(800, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("*{\n"
"    width:25px;\n"
"    height: 15px;\n"
"    background-color: rgb(49, 49, 49);\n"
"    color: rgb(222,222,222);\n"
"    border-radius: 9px;\n"
"}\n"
"*:focus{\n"
"    color: white;\n"
"}\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_2.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_2.setStyleSheet("*{\n"
"    width:25px;\n"
"    height: 15px;\n"
"    background-color: rgb(49, 49, 49);\n"
"    color: rgb(222,222,222);\n"
"    border-radius: 9px;\n"
"}\n"
"*:focus{\n"
"    color: white;\n"
"}\n"
"")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_6.setMinimumSize(QtCore.QSize(0, 45))
        self.pushButton_6.setMaximumSize(QtCore.QSize(45, 45))
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_6.setStyleSheet("*{\n"
"    \n"
"    background-color: transparent;\n"
"}\n"
"*:hover{    \n"
"    \n"
"    border:none;\n"
"    \n"
"    background-color: qradialgradient(spread:pad, cx:0.494, cy:0.505682, radius:0.5, fx:0.5, fy:0.5, stop:0.460227 rgba(156, 58, 108, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"*:pressed{\n"
"    background-color: qradialgradient(spread:pad, cx:0.494, cy:0.505682, radius:0.5, fx:0.5, fy:0.5, stop:0.221591 rgba(156, 58, 108, 255), stop:1 rgba(255, 255, 255, 255));        \n"
"}\n"
"")
        self.pushButton_6.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:/Family Madical Center/minus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon)
        self.pushButton_6.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_2.addWidget(self.pushButton_6)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_5.setMinimumSize(QtCore.QSize(0, 45))
        self.pushButton_5.setMaximumSize(QtCore.QSize(45, 45))
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setStyleSheet("*{\n"
"    \n"
"    background-color: transparent;\n"
"}\n"
"*:hover{    \n"
"    \n"
"    border:none;\n"
"    \n"
"    background-color: qradialgradient(spread:pad, cx:0.494, cy:0.505682, radius:0.5, fx:0.5, fy:0.5, stop:0.460227 rgba(156, 58, 108, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"*:pressed{\n"
"    background-color: qradialgradient(spread:pad, cx:0.494, cy:0.505682, radius:0.5, fx:0.5, fy:0.5, stop:0.221591 rgba(156, 58, 108, 255), stop:1 rgba(255, 255, 255, 255));        \n"
"}\n"
"")
        self.pushButton_5.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:/Family Madical Center/plus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon1)
        self.pushButton_5.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_2.addWidget(self.pushButton_5)
        spacerItem1 = QtWidgets.QSpacerItem(300, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.doc5 = QtWidgets.QPushButton(self.frame_2)
        self.doc5.setMinimumSize(QtCore.QSize(250, 0))
        self.doc5.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.doc5.setFont(font)
        self.doc5.setObjectName("doc5")
        self.horizontalLayout.addWidget(self.doc5)
        self.doc3 = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doc3.sizePolicy().hasHeightForWidth())
        self.doc3.setSizePolicy(sizePolicy)
        self.doc3.setMinimumSize(QtCore.QSize(250, 150))
        self.doc3.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.doc3.setFont(font)
        self.doc3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.doc3.setStyleSheet("*{\n"
"    color:black;\n"
"    background-color: transparent;\n"
"    \n"
"    border-color: rgb(185, 250, 255);\n"
"    border-radius: 9px;\n"
"}\n"
"*:hover{\n"
"    color:white;\n"
"    background-color: rgb(47, 47, 47);\n"
"}\n"
"*:pressed{\n"
"    color:black;\n"
"    background-color: rgb(216, 216, 216);\n"
"}")
        self.doc3.setIconSize(QtCore.QSize(30, 30))
        self.doc3.setObjectName("doc3")
        self.horizontalLayout.addWidget(self.doc3)
        self.doc1 = QtWidgets.QPushButton(self.frame_2)
        self.doc1.setMinimumSize(QtCore.QSize(250, 150))
        self.doc1.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.doc1.setFont(font)
        self.doc1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.doc1.setStyleSheet("*{\n"
"    color:black;\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 9px;\n"
"}\n"
"*:hover{\n"
"    color:white;\n"
"    background-color: rgb(47, 47, 47);\n"
"}\n"
"*:pressed{\n"
"    color:black;\n"
"    background-color: rgb(216, 216, 216);\n"
"}")
        self.doc1.setObjectName("doc1")
        self.horizontalLayout.addWidget(self.doc1)
        self.doc2 = QtWidgets.QPushButton(self.frame_2)
        self.doc2.setMinimumSize(QtCore.QSize(250, 150))
        self.doc2.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.doc2.setFont(font)
        self.doc2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.doc2.setStyleSheet("*{\n"
"    color:black;\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 9px;\n"
"}\n"
"*:hover{\n"
"    color:white;\n"
"    background-color: rgb(47, 47, 47);\n"
"}\n"
"*:pressed{\n"
"    color:black;\n"
"    background-color: rgb(216, 216, 216);\n"
"}")
        self.doc2.setObjectName("doc2")
        self.horizontalLayout.addWidget(self.doc2)
        self.doc4 = QtWidgets.QPushButton(self.frame_2)
        self.doc4.setMinimumSize(QtCore.QSize(250, 150))
        self.doc4.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setFamily("Game Of Squids")
        font.setPointSize(33)
        self.doc4.setFont(font)
        self.doc4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.doc4.setStyleSheet("*{\n"
"    color:black;\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 9px;\n"
"}\n"
"*:hover{\n"
"    color:white;\n"
"    background-color: rgb(47, 47, 47);\n"
"}\n"
"*:pressed{\n"
"    color:black;\n"
"    background-color: rgb(216, 216, 216);\n"
"}")
        self.doc4.setObjectName("doc4")
        self.horizontalLayout.addWidget(self.doc4)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.verticalLayout_2.addWidget(self.frame)
        self.tabs.addTab(self.Home, "")
        self.doctor1 = QtWidgets.QWidget()
        self.doctor1.setObjectName("doctor1")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.doctor1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_6 = QtWidgets.QFrame(self.doctor1)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(900, 25))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(1300, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("*{\n"
"    width:25px;\n"
"    height: 15px;\n"
"    background-color: rgb(49, 49, 49);\n"
"    color: rgb(222,222,222);\n"
"    border-radius: 9px;\n"
"}\n"
"*:focus{\n"
"    color: white;\n"
"}\n"
"")
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_3.setDragEnabled(False)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_8.addWidget(self.lineEdit_3)
        self.label = QtWidgets.QLabel(self.frame_6)
        self.label.setMaximumSize(QtCore.QSize(16777215, 65))
        font = QtGui.QFont()
        font.setFamily("Game Of Squids")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_8.addWidget(self.label)
        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.normal = QtWidgets.QPushButton(self.frame_7)
        self.normal.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.normal.setFont(font)
        self.normal.setCheckable(True)
        self.normal.setObjectName("normal")
        self.horizontalLayout_3.addWidget(self.normal)
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_7.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setCheckable(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_3.addWidget(self.pushButton_7)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_3.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_2.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCheckable(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_4.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setCheckable(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_3.addWidget(self.pushButton_4)
        self.verticalLayout_8.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.frame_6)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.frame_8)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1272, 513))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setGeometry(QtCore.QRect(270, 230, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setGeometry(QtCore.QRect(170, 180, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setGeometry(QtCore.QRect(160, 250, 47, 13))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setGeometry(QtCore.QRect(330, 310, 47, 13))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setGeometry(QtCore.QRect(310, 120, 47, 13))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setGeometry(QtCore.QRect(160, 100, 47, 13))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setGeometry(QtCore.QRect(50, 220, 47, 13))
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setGeometry(QtCore.QRect(90, 340, 47, 13))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setGeometry(QtCore.QRect(570, 320, 47, 13))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setGeometry(QtCore.QRect(550, 160, 47, 13))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_13.setGeometry(QtCore.QRect(450, 240, 47, 13))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_14.setGeometry(QtCore.QRect(440, 300, 47, 13))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_15.setGeometry(QtCore.QRect(420, 322, 47, 271))
        self.label_15.setObjectName("label_15")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.verticalLayout_8.addWidget(self.frame_8)
        self.verticalLayout_7.addWidget(self.frame_6)
        self.tabs.addTab(self.doctor1, "")
        self.doctor2 = QtWidgets.QWidget()
        self.doctor2.setObjectName("doctor2")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.doctor2)
        self.lineEdit_4.setGeometry(QtCore.QRect(0, 20, 1300, 25))
        self.lineEdit_4.setMinimumSize(QtCore.QSize(900, 25))
        self.lineEdit_4.setMaximumSize(QtCore.QSize(1300, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("*{\n"
"    width:25px;\n"
"    height: 15px;\n"
"    background-color: rgb(49, 49, 49);\n"
"    color: rgb(222,222,222);\n"
"    border-radius: 9px;\n"
"}\n"
"*:focus{\n"
"    color: white;\n"
"}\n"
"")
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_4.setDragEnabled(False)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.tabs.addTab(self.doctor2, "")
        self.search_tab = QtWidgets.QWidget()
        self.search_tab.setObjectName("search_tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.search_tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_4 = QtWidgets.QFrame(self.search_tab)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.search_label = QtWidgets.QLabel(self.frame_4)
        self.search_label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Game Of Squids")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.search_label.setFont(font)
        self.search_label.setAlignment(QtCore.Qt.AlignCenter)
        self.search_label.setObjectName("search_label")
        self.verticalLayout_5.addWidget(self.search_label)
        self.verticalLayout_4.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.search_tab)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_9 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_6.addWidget(self.label_9)
        self.verticalLayout_4.addWidget(self.frame_5)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.search_tab)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(800, 25))
        self.lineEdit_5.setMaximumSize(QtCore.QSize(1300, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("*{\n"
"    width:25px;\n"
"    height: 15px;\n"
"    background-color: rgb(49, 49, 49);\n"
"    color: rgb(222,222,222);\n"
"    border-radius: 9px;\n"
"}\n"
"*:focus{\n"
"    color: white;\n"
"}\n"
"")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_4.addWidget(self.lineEdit_5)
        self.tabs.addTab(self.search_tab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabs.addTab(self.tab, "")
        self.horizontalLayout_4.addWidget(self.tabs)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1338, 21))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        self.menunothing_for_now = QtWidgets.QMenu(self.menufile)
        self.menunothing_for_now.setObjectName("menunothing_for_now")
        self.menuusing_code_for_it = QtWidgets.QMenu(self.menunothing_for_now)
        self.menuusing_code_for_it.setObjectName("menuusing_code_for_it")
        MainWindow.setMenuBar(self.menubar)
        self.actionend = QtWidgets.QAction(MainWindow)
        self.actionend.setObjectName("actionend")
        self.menuusing_code_for_it.addAction(self.actionend)
        self.menunothing_for_now.addAction(self.menuusing_code_for_it.menuAction())
        self.menufile.addAction(self.menunothing_for_now.menuAction())
        self.menubar.addAction(self.menufile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Home.setToolTip(_translate("MainWindow", "Home"))
        self.mai_text.setToolTip(_translate("MainWindow", "<html><head/><body><p>Hospital</p></body></html>"))
        self.mai_text.setText(_translate("MainWindow", "Family Madical Center"))
        self.doc5.setText(_translate("MainWindow", "ABC"))
        self.doc3.setText(_translate("MainWindow", "Dr.Azra Haneef"))
        self.doc1.setText(_translate("MainWindow", "Dr.Abida Raza"))
        self.doc2.setText(_translate("MainWindow", "Lab"))
        self.doc4.setText(_translate("MainWindow", "abc"))
        self.tabs.setTabText(self.tabs.indexOf(self.Home), _translate("MainWindow", "Tab 1"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "  Search Here..."))
        self.label.setToolTip(_translate("MainWindow", "Doctor"))
        self.label.setText(_translate("MainWindow", "DR.AZRA HANEEF"))
        self.normal.setText(_translate("MainWindow", "Normal"))
        self.pushButton_7.setText(_translate("MainWindow", "Emergency"))
        self.pushButton_3.setText(_translate("MainWindow", "Delevery"))
        self.pushButton_2.setText(_translate("MainWindow", "D and E"))
        self.pushButton_4.setText(_translate("MainWindow", "C-"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.label_5.setText(_translate("MainWindow", "TextLabel"))
        self.label_6.setText(_translate("MainWindow", "TextLabel"))
        self.label_7.setText(_translate("MainWindow", "TextLabel"))
        self.label_8.setText(_translate("MainWindow", "TextLabel"))
        self.label_10.setText(_translate("MainWindow", "TextLabel"))
        self.label_11.setText(_translate("MainWindow", "TextLabel"))
        self.label_12.setText(_translate("MainWindow", "TextLabel"))
        self.label_13.setText(_translate("MainWindow", "TextLabel"))
        self.label_14.setText(_translate("MainWindow", "TextLabel"))
        self.label_15.setText(_translate("MainWindow", "TextLabel"))
        self.tabs.setTabText(self.tabs.indexOf(self.doctor1), _translate("MainWindow", "Tab 2"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "  Search Here..."))
        self.tabs.setTabText(self.tabs.indexOf(self.doctor2), _translate("MainWindow", "Page"))
        self.search_label.setText(_translate("MainWindow", "SEARCH RESULT HERE"))
        self.label_9.setText(_translate("MainWindow", " NAME: BAREERA \n"
" FEE: 500 \n"
" DATE: 25/2/2023  \n"
"\n"
" NAME: NOOR \n"
" FEE: 500 \n"
" DATE: 25/2/2023 \n"
"\n"
" NAME: ABC \n"
" FEE: 500 \n"
" DATE: 25/2/2023 \n"
"\n"
" NAME: RASHID \n"
" FEE: 500 \n"
" DATE: 25/2/2023 "))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "  Search Here.."))
        self.tabs.setTabText(self.tabs.indexOf(self.search_tab), _translate("MainWindow", "Page"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab), _translate("MainWindow", "Page"))
        self.menufile.setTitle(_translate("MainWindow", "file"))
        self.menunothing_for_now.setTitle(_translate("MainWindow", "nothing for now"))
        self.menuusing_code_for_it.setTitle(_translate("MainWindow", "using code for it"))
        self.actionend.setText(_translate("MainWindow", "end"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
